import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home = (props) => {
  console.log('jome', props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/about">About</Link>
      </main>
    </div>
  );
};

//这个方法在服务端运行,但是在编译是决定了,所以不能拿用户的动态数据
// export const getStaticProps = async () => {
//   return {
//     props: {
//       yy: Math.random(),
//     },
//   };
// };

export const getServerSideProps = async (ctx) => {
  // console.log(ctx.params, ctx.query, ctx);
  return {
    props: {
      yy: Math.random(),
    },
  };
};
export default Home;

// Home.getInitialProps = (ctx) => {
//   return { xx: 'x' };
// };
